name: Auto-update list

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: git config user.name "TLDS Bot"
      - run: git config user.email "me@stephenmathieson.com"
      - run: npm install
      - run: node cron
